### ISSUE TITLE
Marking required fields in forms

### ISSUE THREAD

**Issue by h22y25n** [spaceone-dev/console#3089]
In `My Page > Add Notifications Channel`
`Save` button is disabled, but user can't understand why. and how can they Save.
Marking required fields in forms can improve usability of forms.

![Image](https://user-images.githubusercontent.com/65589909/179897768-415cc169-86f8-4511-be0e-dc093db8d8cf.png)

**Comment by WANZARGEN** [comment]
This is UX issue and discussion required
