### ISSUE TITLE
Create link only available resources from Cost in Cost Analysis Page

### ISSUE THREAD

**Issue by whdalsrnt** [spaceone-dev/console#3214]
![image](https://user-images.githubusercontent.com/15934888/161695590-7d21ce47-2b75-4452-8de6-136db791b0b3.png)

Reference:
![image](https://user-images.githubusercontent.com/15934888/161695665-9500e68f-ea4c-4abc-8605-d6067c379a6a.png)

**Comment by WANZARGEN** [comment]
It's not working!

**Comment by yuda110** [comment]
This issue has been closed due to development difficulties.
