### ISSUE TITLE
Change the x-axis time of the monitoring chart

### ISSUE THREAD

**Issue by whdalsrnt** [spaceone-dev/console#3379]
![image](https://user-images.githubusercontent.com/15934888/160247887-48092c2a-38c0-486f-92d4-4457553e5c21.png)

As-is: Date Only
To-be: Dynamic Time (Minute ~ Hour ~ Date)

**Comment by yuda110** [comment]
It seems to have been resolved.

![스크린샷 2022-09-13 오전 9 49 02](https://user-images.githubusercontent.com/18563857/189783515-e7afe2b3-e250-459a-94c0-46d7da94078b.png)
